import {build} from "esbuild";
import {readFile, writeFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const metadata = JSON.parse(await readFile(new URL("../src/metadata.json", import.meta.url), "utf8"));
const header = "/**\n" + Object.entries(metadata).map(([key, value]) => ` * @${key} ${value}`).join("\n") + "\n */";
const licenses = await Promise.all(["post-quantum", "hashes", "ciphers"].map(async name =>
    `@noble/${name}\n\n` + await readFile(new URL(`../node_modules/@noble/${name}/LICENSE`, import.meta.url), "utf8")));
const notices = licenses.join("\n\n");
await build({
    absWorkingDir: root,
    entryPoints: ["src/plugin.js"],
    outfile: "qcord.plugin.js",
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "es2020",
    loader: {".css": "text", ".svg": "text"},
    legalComments: "inline",
    banner: {js: `${header}\n\n// Generated by npm run build. Edit src/ instead.\n/*\n${notices}\n*/`},
    logLevel: "info"
});
await writeFile(new URL("../THIRD_PARTY_NOTICES.md", import.meta.url), notices);
